### ISSUE TITLE
Einzelne Menüpunkte für jedes Logfile

### ISSUE THREAD

**Issue by cliffparnitzky** [FlxPeters/wd_logs#2]
Wäre super, wenn die Logfiles als einzelne Menüpunkte aufgeführt werden.

**Comment by FlxPeters** [comment]
Hi,

ich bin nicht mehr im Contao Orbit unterwegs. Willst du das Projekt übernehmen?

**Comment by cliffparnitzky** [comment]
@FlxPeters hab da schon lange nen stark modifizierten Fork ...

**Comment by FlxPeters** [comment]
Ok, danke für die Info!
